import streamlit as st
import pandas as pd
import time
import plotly.graph_objects as go
import os

st.set_page_config(page_title="SOC Dashboard: Live IDS", layout="wide")
st.title("🛡️ Real-Time Endpoint Detection & Response (EDR)")
st.markdown("Monitoring live hardware network traffic using Unsupervised Machine Learning.")

# --- File Setup ---
DATA_FILE = 'live_traffic.csv'
THRESHOLD = -0.11  # Match the threshold from your sniffer

# --- Layout ---
col1, col2, col3 = st.columns(3)
kpi_total = col1.empty()
kpi_alerts = col2.empty()
kpi_status = col3.empty()

st.divider()

chart_placeholder = st.empty()

st.subheader("🚨 Critical Threat Log")
log_placeholder = st.empty()

# --- The Live Stream Engine ---
is_monitoring = st.toggle("▶️ Start Live Telemetry")

if is_monitoring:
    if os.path.exists(DATA_FILE):
        try:
            # 1. Read the live data generated by Scapy
            df = pd.read_csv(DATA_FILE)
            
            if not df.empty:
                # 2. Calculate KPIs
                total_scans = len(df)
                alerts_df = df[df['Status'] == 'ALERT']
                total_alerts = len(alerts_df)
                
                kpi_total.metric(label="Packets Scanned", value=total_scans)
                kpi_alerts.metric(label="Threats Blocked", value=total_alerts)
                
                if total_alerts > 0:
                    kpi_status.metric(label="System Status", value="🔴 BREACH DETECTED")
                else:
                    kpi_status.metric(label="System Status", value="🟢 SECURE")
                
                # 3. Update the Live Chart (Show last 100 packets for performance)
                plot_data = df.tail(100)
                fig = go.Figure()
                
                # Plot normal traffic
                fig.add_trace(go.Scatter(
                    y=plot_data['Score'],
                    mode='lines+markers',
                    name='Anomaly Score',
                    line=dict(color='#00F0FF')
                ))
                
                # Draw the hard threshold line
                fig.add_hline(y=THRESHOLD, line_dash="dash", line_color="red", annotation_text="Defense Threshold")
                
                fig.update_layout(
                    height=400, 
                    title="Real-Time Network Anomaly Telemetry", 
                    yaxis_title="AI Score", 
                    xaxis_title="Packet Stream (Latest)",
                    template="plotly_dark"
                )
                chart_placeholder.plotly_chart(fig, use_container_width=True)
                
                # 4. Update the Alert Table
                # Reverse the alerts dataframe so the newest ones are at the top
                log_placeholder.dataframe(alerts_df.tail(15).iloc[::-1], use_container_width=True, hide_index=True)
                
        except Exception as e:
            # If Pandas tries to read the exact millisecond Scapy is writing, it might throw an error.
            # We just pass and wait for the next second.
            pass
            
    # --- The Magic Loop ---
    # Pause for 1 second, then automatically rerun the entire Streamlit script to pull fresh data
    time.sleep(1)
    st.rerun()
else:
    st.info("Telemetry offline. Toggle the switch to connect to the AI engine.")